version: '3'
services:
    npm:
        image: digitallyseamless/nodejs-bower-grunt
        ports:
            - "1337:1337"
        command: npm start
networks:
    default:
        external:
            name: local
